# Generated by Django 4.1.2 on 2023-01-23 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_chatcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatcontent',
            name='sentOn',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
