# Generated by Django 4.1.2 on 2023-01-23 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_chatcontent_senton'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatcontent',
            name='sentOn',
        ),
        migrations.AlterField(
            model_name='chatcontent',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
