# Generated by Django 4.1.2 on 2023-01-23 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_chatcontent_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatcontent',
            name='time',
            field=models.TimeField(default=datetime.time(23, 51, 59, 325410)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default="hey, I'm using megagram"),
        ),
    ]
