# Generated by Django 4.1.2 on 2023-01-24 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_chatcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatcontent',
            name='time',
            field=models.TimeField(default=datetime.time(21, 47, 15, 596300)),
        ),
        migrations.AlterField(
            model_name='posttest',
            name='userPro',
            field=models.ImageField(blank=True, upload_to='post_userPro'),
        ),
    ]
