# Generated by Django 4.1.2 on 2023-01-24 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_chatcontent_time_alter_posttest_userpro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatcontent',
            name='time',
            field=models.TimeField(default=datetime.time(21, 53, 7, 980923)),
        ),
        migrations.AlterField(
            model_name='posttest',
            name='userPro',
            field=models.ImageField(default='', upload_to='post_userPro'),
        ),
    ]
