# Generated by Django 4.1.2 on 2023-01-25 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_comments_alter_chatcontent_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='dummyPro',
            field=models.ImageField(default='', upload_to='dummyPro'),
        ),
        migrations.AlterField(
            model_name='chatcontent',
            name='time',
            field=models.TimeField(default=datetime.time(20, 52, 3, 731906)),
        ),
    ]
